<?php

include('header.php');

?>

<div class="row">
	<div class="content column small-12">
		<div class="box column small-12 medium-12">
			<div class="box-content">
				<div class="box-content-line">
					<div class="box-content-title">
						Terms of Service
					</div>
				</div>

				<div class="box-content-line">
					<span class="tos-title">TERMS OF USE</span>
					<br>
					<div class="tos-content">
						BY ACCESSING OR USING WWW.NORTHCRAFT.ORG (THE "SITE") AND ITS SERVICES (THE "SERVICES"), YOU (THE "USER") AGREE TO COMPLY WITH THE TERMS AND CONDITIONS GOVERNING THE USER'S USE OF ANY AREAS OF THE SITE AND AFFILIATED SERVICES AS SET FORTH BELOW. 
					</div>
					<br>
					<br>
					<span class="tos-title">USE OF SITE</span>
					<br>
					<div class="tos-content">
						THIS SITE OR ANY PORTION OF THE SITE AS WELL AS THE SERVICES MAY NOT BE REPRODUCED, DUPLICATED, COPIED, SOLD, RESOLD, OR OTHERWISE EXPLOITED FOR ANY COMMERCIAL PURPOSE EXCEPT AS EXPRESSLY PERMITTED BY NORTHCRAFT.ORG. NORTHCRAFT RESERVES THE RIGHT TO REFUSE SERVICE IN ITS DISCRETION, WITHOUT LIMITATION, IF NORTHCRAFT BELIEVES THE USER CONDUCT VIOLATES APPLICABLE LAW OR IS HARMFUL TO THE INTERESTS OF NORTHCRAFT, OTHER USERS OF THE SITE AND THE SERVICES OR ITS AFFILIATES. 
					</div>
					<br>
					<br>
					<span class="tos-title">USE OF SERVICES</span>
					<br>
					<div class="tos-content">
						NORTHCRAFT.ORG IS A NON-PROFIT PROJECT DEVELOPED TO IMITATE OUTDATED GAME VERSIONS FOR EDUCATIONAL PURPOSES ONLY. THE SITE AND THE SERVICES DO NOT SUPPORT AND DO NOT PROVIDE ANY MODIFICATION TO GAME FILES. BY USING THE SITE OR THE SERVICES, THE USER AGREES TO TAKE RESPONSIBILITY TO FOLLOW GAME’S EULA. 
					</div>
					<br>
					<br>
					<span class="tos-title">DISTRIBUTION</span>
					<br>
					<div class="tos-content">
						NORTHCRAFT.ORG DOES NOT SUPPORT DISTRIBUTION OF ANY GAME CLIENTS. DOWNLOAD LINKS ON THE SITE CONSTITUTE MIRRORS OF EXTERNAL SITES FOR EDUCATIONAL PURPOSES. 
					</div>
					<br>
					<br>
					<span class="tos-title">SITE ACCOUNT</span>
					<br>
					<div class="tos-content">
						THE USER MAY REGISTER A REGULAR ACCOUNT AND PASSWORD FOR THE SERVICE FOR FREE. YOU ARE RESPONSIBLE FOR ALL ACTIVITY UNDER YOUR ACCOUNT, ASSOCIATED ACCOUNTS, AND PASSWORDS. THE SITE IS NOT RESPONSIBLE FOR UNAUTHORISED ACCESS TO YOUR ACCOUNT, AND ANY LOSS OF VIRTUAL ITEMS ASSOCIATED WITH IT. EVENTS, VIDEOS AND COMMUNITY CREATIONS UPON REGISTERING AN ACCOUNT, YOU AGREE THAT YOUR ACCOUNT OR CHARACTERS MAY BE INCLUDED IN ANY EVENTS, STREAMS OR VIDEOS FOR PROMOTION OR REVIEW PURPOSES. 
					</div>
					<br>
					<br>
					<span class="tos-title">ACCESS TO THE SITE AND SERVICES</span>
					<br>
					<div class="tos-content">
						NORTHCRAFT PROVIDES FREE AND UNLIMITED ACCESS TO THE SITE AND THE SERVICES. 
					</div>
					<br>
					<br>
					<span class="tos-title">SUBMISSION</span>
					<br>
					<div class="tos-content">
						NORTHCRAFT DOES NOT ASSUME ANY OBLIGATION WITH RESPECT TO ANY SUBMISSION AND NO CONFIDENTIAL OR FIDUCIARY UNDERSTANDING OR RELATIONSHIP IS ESTABLISHED BY THE SITE'S RECEIPT OR ACCEPTANCE OF ANY SUBMISSION. ALL SUBMISSIONS BECOME THE EXCLUSIVE PROPERTY OF THE SITE AND ITS AFFILIATES. THE SITE AND ITS AFFILIATES MAY USE ANY SUBMISSION WITHOUT RESTRICTION AND THE USER SHALL NOT BE ENTITLED TO ANY COMPENSATION. 
					</div>
					<br>
					<br>
					<span class="tos-title">THIRD-PARTY CONTENT</span>
					<br>
					<div class="tos-content">
						NEITHER NORTHCRAFT, NOR ITS AFFILIATES, NOR ANY OF THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, NOR ANY THIRD PARTY, INCLUDING ANY PROVIDER/AFFILIATE, OR ANY OTHER USER OF THE SITE AND SERVICES, GUARANTEES THE ACCURACY, COMPLETENESS, OR USEFULNESS OF ANY CONTENT, NOR ITS MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE. IN SOME INSTANCES, THE CONTENT AVAILABLE THROUGH THE SITE MAY REPRESENT THE OPINIONS AND JUDGMENTS OF PROVIDERS/AFFILIATES OR USERS. NORTHCRAFT AND ITS AFFILIATES DO NOT ENDORSE AND SHALL NOT BE RESPONSIBLE FOR THE ACCURACY OR RELIABILITY OF ANY OPINION, ADVICE, OR STATEMENT MADE ON THE SITE AND THE SERVICES BY ANYONE OTHER THAN AUTHORISED NORTHCRAFT EMPLOYEES. UNDER NO CIRCUMSTANCES SHALL NORTHCRAFT, OR ITS AFFILIATES, OR ANY OF THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY LOSS, DAMAGE OR HARM CAUSED BY A USER'S RELIANCE ON INFORMATION OBTAINED THROUGH THE SITE AND THE SERVICES. IT IS THE RESPONSIBILITY OF THE USER TO EVALUATE THE INFORMATION, OPINION, ADVICE, OR OTHER CONTENT AVAILABLE THROUGH THIS SITE. 
					</div>
					<br>
					<br>
					<span class="tos-title">DISCLAIMERS AND LIMITATION OF LIABILITY</span>
					<br>
					<div class="tos-content">
						USER AGREES THAT USE OF THE SITE AND THE SERVICES IS AT THE USER'S SOLE RISK. NEITHER NORTHCRAFT, NOR ITS AFFILIATES, NOR ANY OF THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, THIRD-PARTY CONTENT PROVIDERS, MERCHANTS, SPONSORS, LICENSORS OR THE LIKE (COLLECTIVELY, "PROVIDERS"), WARRANT THAT THE SITE AND THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE; NOR DO THEY MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SITE AND THE SERVICES, OR AS TO THE ACCURACY, RELIABILITY, OR CURRENCY OF ANY INFORMATION CONTENT, SERVICE, OR MERCHANDISE PROVIDED THROUGH THIS SITE. THE SITE AND THE SERVICES ARE PROVIDED BY NORTHCRAFT ON AN "AS IS" AND "AS AVAILABLE" BASIS. THE SITE MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THE SITE, THE INFORMATION, CONTENT, MATERIALS OR PRODUCTS, INCLUDED ON THIS SITE. TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, THE SITE DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. NORTHCRAFT WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THE SITE AND THE SERVICES, INCLUDING BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL, PUNITIVE AND CONSEQUENTIAL DAMAGES. UNDER NO CIRCUMSTANCES SHALL NORTHCRAFT OR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DISTRIBUTING THE SITE AND THE SERVICES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES THAT RESULT FROM THE USE OF OR INABILITY TO USE THE SITE AND THE SERVICES, INCLUDING BUT NOT LIMITED TO RELIANCE BY THE USER ON ANY INFORMATION OBTAINED FROM THE SITE OR THAT RESULT FROM MISTAKES, OMISSIONS, INTERRUPTIONS, DELETION OF FILES OR EMAIL, ERRORS, DEFECTS, VIRUSES, DELAYS IN OPERATION OR TRANSMISSION, OR ANY FAILURE OF PERFORMANCE, WHETHER OR NOT RESULTING FROM ACTS OF GOD, COMMUNICATIONS FAILURE, THEFT, DESTRUCTION, OR UNAUTHORISED ACCESS TO THE SITE'S RECORDS, PROGRAMS, OR SERVICES. THE USER HEREBY ACKNOWLEDGES THAT THESE DISCLAIMERS AND LIMITATION ON LIABILITY SHALL APPLY TO ALL CONTENT, MERCHANDISE, AND SERVICES AVAILABLE THROUGH THE SITE AND THE SERVICES. IN STATES THAT DO NOT ALLOW THE EXCLUSION OF LIMITATION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE USER AGREES THAT LIABILITY IN SUCH STATES SHALL BE LIMITED TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW. 
					</div>
					<br>
					<br>
					<span class="tos-title">TERMINATION OF SERVICE</span>
					<br>
					<div class="tos-content">
						NORTHCRAFT RESERVES THE RIGHT, IN ITS SOLE DISCRETION, TO CHANGE, SUSPEND, LIMIT, OR DISCONTINUE ANY ASPECT OF THE SERVICE AND THE SERVICES AT ANY TIME. NORTHCRAFT MAY SUSPEND OR TERMINATE ANY USER'S ACCESS TO ALL OR PART OF THE SITE AND THE SERVICES, WITHOUT NOTICE, FOR ANY CONDUCT THAT NORTHCRAFT, IN ITS SOLE DISCRETION, BELIEVES IS IN VIOLATION OF THESE TERMS AND CONDITIONS. 
					</div>
					<br>
					<br>
					<span class="tos-title">DONATIONS</span>
					<br>
					<div class="tos-content">
						DONATIONS ARE MADE ON A VOLUNTARY BASIS IN APPRECIATION OF THE SITE AND THE SERVICES. NORTHCRAFT DOES NOT ASSUME ANY FINANCIAL OBLIGATION WITH RESPECT TO DONATIONS. THE USER MUST BE OVER 18 TO BE ELIGIBLE TO MAKE A DONATION TO NORTHCRAFT. NORTHCRAFT IS NOT LIABLE FOR ANY UNAUTHORIZED DONATIONS. 
					</div>
					<br>
					<br>
					<span class="tos-title">ACKNOWLEDGEMENT</span>
					<br>
					<div class="tos-content">
						BY ACCESSING OR USING THE SITE AND THE SERVICES, THE USER AGREES TO BE BOUND BY THESE TERMS AND CONDITIONS, INCLUDING DISCLAIMERS. NORTHCRAFT RESERVES THE RIGHT TO MAKE CHANGES TO THE SITE AND THESE TERMS AND CONDITIONS, INCLUDING DISCLAIMERS, AT ANY TIME. IF YOU DO NOT AGREE TO THE PROVISIONS OF THIS AGREEMENT OR ARE NOT SATISFIED WITH THE SERVICE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE YOUR USE OF THE SERVICE. 
					</div>
					<br>
					<br>
					<span class="tos-title">PRIVACY STATEMENT</span>
					<br>
					<div class="tos-content">
						CERTAIN USER INFORMATION COLLECTED THROUGH THE USE OF THIS WEBSITE IS AUTOMATICALLY STORED FOR REFERENCE. WE TRACK SUCH INFORMATION TO PERFORM INTERNAL RESEARCH ON OUR USERS' DEMOGRAPHIC INTERESTS AND BEHAVIOUR AND TO BETTER UNDERSTAND, PROTECT AND SERVE OUR COMMUNITY OF USERS. PAYMENT OR ANY OTHER FINANCIAL INFORMATION IS NEVER SUBMITTED, DISCLOSED OR STORED ON THE SITE AND IS BOUND TO TERMS AND CONDITIONS AND PRIVACY POLICY OF OUR RESPECTIVE PARTNERS AND/OR PAYMENT PROCESSORS. BASIC USER INFORMATION (SUCH AS IP ADDRESS, LOGS FOR USING WEBSITE INTERFACE AND ACCOUNT MANAGEMENT) MAY BE DISCLOSED TO OUR PARTNERS IN MUTUAL EFFORTS TO COUNTER POTENTIAL ILLEGAL ACTIVITIES. NORTHCRAFT MAKES SIGNIFICANT EFFORT TO PROTECT SUBMITTED INFORMATION TO PREVENT UNAUTHORISED ACCESS TO THAT INFORMATION IN ITS INTERNAL PROCEDURES AND TECHNOLOGY. HOWEVER, WE DO NOT GUARANTEE, NOR SHOULD YOU EXPECT, THAT YOUR PERSONAL INFORMATION AND PRIVATE COMMUNICATIONS WILL ALWAYS REMAIN PRIVATE.
					</div>
					<br>
				</div>
			</div>
		</div>
	</div>
</div>

<?php

include('footer.php');

?>